level_0 = {
		'coins': '/Users/Serena/PycharmProjects/GApp/levels/0/level_0_coins.csv',
		'constraints': '/Users/Serena/PycharmProjects/GApp/levels/0/level_0_constraint.csv',
		'crates': '/Users/Serena/PycharmProjects/GApp/levels/0/level_0_crates.csv',
		'enemy': '/Users/Serena/PycharmProjects/GApp/levels/0/level_0_enemy.csv',
		'gems': '/Users/Serena/PycharmProjects/GApp/levels/0/level_0_gems.csv',
		'grass': '/Users/Serena/PycharmProjects/GApp/levels/0/level_0_grass.csv',
		'maps': '/Users/Serena/PycharmProjects/GApp/levels/0/level_0_maps.csv',
		'platforms': '/Users/Serena/PycharmProjects/GApp/levels/0/level_0_platforms.csv',
		'player': '/Users/Serena/PycharmProjects/GApp/levels/0/level_0_player.csv',
		'spikes': '/Users/Serena/PycharmProjects/GApp/levels/0/level_0_spikes.csv',
		'terrain': '/Users/Serena/PycharmProjects/GApp/levels/0/level_0_terrain.csv',
		'trees': '/Users/Serena/PycharmProjects/GApp/levels/0/level_0_trees.csv',
		'node_pos': (180,200),
		'unlock': 1,
		'node_graphics': '/Users/Serena/PycharmProjects/GApp/graphics/overworld/0'}
level_1 = {
		'coins': '/Users/Serena/PycharmProjects/GApp/levels/1/level_1_coins.csv',
		'constraints': '/Users/Serena/PycharmProjects/GApp/levels/1/level_1_constraint.csv',
		'crates': '/Users/Serena/PycharmProjects/GApp/levels/1/level_1_crates.csv',
		'enemy': '/Users/Serena/PycharmProjects/GApp/levels/1/level_1_enemy.csv',
		'gems': '/Users/Serena/PycharmProjects/GApp/levels/1/level_1_gems.csv',
		'grass': '/Users/Serena/PycharmProjects/GApp/levels/1/level_1_grass.csv',
		'maps': '/Users/Serena/PycharmProjects/GApp/levels/1/level_1_maps.csv',
		'platforms': '/Users/Serena/PycharmProjects/GApp/levels/1/level_1_platforms.csv',
		'player': '/Users/Serena/PycharmProjects/GApp/levels/1/level_1_player.csv',
		'spikes': '/Users/Serena/PycharmProjects/GApp/levels/1/level_1_spikes.csv',
		'terrain': '/Users/Serena/PycharmProjects/GApp/levels/1/level_1_terrain.csv',
		'trees': '/Users/Serena/PycharmProjects/GApp/levels/1/level_1_trees.csv',
		'node_pos': (480,700),
		'node_graphics': '/Users/Serena/PycharmProjects/GApp/graphics/overworld/1',
		'unlock': 2}
level_2 = {
		'coins': '/Users/Serena/PycharmProjects/GApp/levels/2/level_2_coins.csv',
		'constraints': '/Users/Serena/PycharmProjects/GApp/levels/2/level_2_constraint.csv',
		'crates': '/Users/Serena/PycharmProjects/GApp/levels/2/level_2_crates.csv',
		'enemy': '/Users/Serena/PycharmProjects/GApp/levels/2/level_2_enemy.csv',
		'gems': '/Users/Serena/PycharmProjects/GApp/levels/2/level_2_gems.csv',
		'grass': '/Users/Serena/PycharmProjects/GApp/levels/2/level_2_grass.csv',
		'maps': '/Users/Serena/PycharmProjects/GApp/levels/2/level_2_maps.csv',
		'platforms': '/Users/Serena/PycharmProjects/GApp/levels/2/level_2_platforms.csv',
		'player': '/Users/Serena/PycharmProjects/GApp/levels/2/level_2_player.csv',
		'spikes': '/Users/Serena/PycharmProjects/GApp/levels/2/level_2_spikes.csv',
		'terrain': '/Users/Serena/PycharmProjects/GApp/levels/2/level_2_terrain.csv',
		'trees': '/Users/Serena/PycharmProjects/GApp/levels/2/level_2_trees.csv',
		'node_pos': (780,350),
		'node_graphics': '/Users/Serena/PycharmProjects/GApp/graphics/overworld/2',
		'unlock': 3}
level_3 = {
		'coins': '/Users/Serena/PycharmProjects/GApp/levels/3/level_3_coins.csv',
		'constraints': '/Users/Serena/PycharmProjects/GApp/levels/3/level_3_constraint.csv',
		'crates': '/Users/Serena/PycharmProjects/GApp/levels/3/level_3_crates.csv',
		'enemy': '/Users/Serena/PycharmProjects/GApp/levels/3/level_3_enemy.csv',
		'gems': '/Users/Serena/PycharmProjects/GApp/levels/3/level_3_gems.csv',
		'grass': '/Users/Serena/PycharmProjects/GApp/levels/3/level_3_grass.csv',
		'maps': '/Users/Serena/PycharmProjects/GApp/levels/3/level_3_maps.csv',
		'platforms': '/Users/Serena/PycharmProjects/GApp/levels/3/level_3_platforms.csv',
		'player': '/Users/Serena/PycharmProjects/GApp/levels/3/level_3_player.csv',
		'spikes': '/Users/Serena/PycharmProjects/GApp/levels/3/level_3_spikes.csv',
		'terrain': '/Users/Serena/PycharmProjects/GApp/levels/3/level_3_terrain.csv',
		'trees': '/Users/Serena/PycharmProjects/GApp/levels/3/level_3_trees.csv',
		'node_pos': (1080,700),
		'node_graphics': '/Users/Serena/PycharmProjects/GApp/graphics/overworld/3',
		'unlock': 4}
level_4 = {
		'coins': '/Users/Serena/PycharmProjects/GApp/levels/5/level_5_coins.csv',
		'constraints': '/Users/Serena/PycharmProjects/GApp/levels/5/level_5_constraint.csv',
		'crates': '/Users/Serena/PycharmProjects/GApp/levels/5/level_5_crates.csv',
		'enemy': '/Users/Serena/PycharmProjects/GApp/levels/5/level_5_enemy.csv',
		'gems': '/Users/Serena/PycharmProjects/GApp/levels/5/level_5_gems.csv',
		'grass': '/Users/Serena/PycharmProjects/GApp/levels/5/level_5_grass.csv',
		'maps': '/Users/Serena/PycharmProjects/GApp/levels/5/level_5_maps.csv',
		'platforms': '/Users/Serena/PycharmProjects/GApp/levels/5/level_5_platforms.csv',
		'player': '/Users/Serena/PycharmProjects/GApp/levels/5/level_5_player.csv',
		'spikes': '/Users/Serena/PycharmProjects/GApp/levels/5/level_5_spikes.csv',
		'terrain': '/Users/Serena/PycharmProjects/GApp/levels/5/level_5_terrain.csv',
		'trees': '/Users/Serena/PycharmProjects/GApp/levels/5/level_5_trees.csv',
		'node_pos': (1380,200),
		'unlock': 4,
		'node_graphics': '/Users/Serena/PycharmProjects/GApp/graphics/overworld/4'
}

levels = {
	0: level_0,
	1: level_1,
	2: level_2,
	3: level_3,
	4: level_4}